### ISSUE TITLE
[BUG] Content de um alert sem "onRemove" não ocupa toda a largura

### ISSUE THREAD

**Issue by giovanna-abrantes** [TiendaNube/nimbus-design-system#130]
🐛 **Describe the bug**
Quando tiramos o "x" de um alert, o conteúdo do mesmo não ocupa toda a largura, mesmo usando o fill.

🧐 **To Reproduce**
Steps to reproduce the behavior

1. Desligue "onRemove"
2. Aplique "fill" ao conteúdo do alert

✅ **Expected behavior**
Que o conteúdo ocupe todo o espaço, com padding 16px.

📷 **Screenshots**

![Captura de Tela 2023-03-22 às 19 24 54](https://user-images.githubusercontent.com/107882097/227054449-71213d68-cc2f-4ff9-916b-22b4e57248aa.png)

**Comment by jcampos89** [comment]
@giovanna-abrantes obrigado por reportar! Levamos essa issue ao nosso backlog, estamos analisando se afeta somente o Figma ou também na versão react, assim que tivermos updates comunico aqui.

**Comment by juniorconquista** [comment]
@giovanna-abrantes primeiramente muito obrigado pela sua contribuição identificamos que o erro também foi replicado em codigo na versão react, porem ja foi corrigido na data de ontem no seguinte [#134](https://github.com/TiendaNube/nimbus-design-system/pull/134) para ter as correções basta apenas atualizar os pacotes do nimbus nos projetos.
