### ISSUE TITLE
[BUG] Inclusão de prop as no menu button

### ISSUE THREAD

**Issue by jcampos89** [TiendaNube/nimbus-design-system#131]
### Discussed in https://github.com/TiendaNube/nimbus-design-system/discussions/125

<div type='discussions-op-text'>

<sup>Originally posted by **hrchioest** March 17, 2023</sup>
Estoy viendo [este issue](https://github.com/TiendaNube/issues/issues/24345) donde, desde el  menú al hacer click derecho no te da la opción para abrirlo en una nueva pestaña, ya que están construidos como si fuesen botones ¿Qué componente recomiendan que pueda usar ya que internamente tendría que ser como un elemento a, estuve revisando el componente MenuButton pero internamente tiene un button y un elemento p. Me dan ideas por favor? Desde ya gracias! </div>

**Comment by jcampos89** [comment]
[ECNIM-714](https://tiendanube.atlassian.net/browse/ECNIM-714)
https://tiendanube.atlassian.net/browse/ECNIM-714

**Comment by juniorconquista** [comment]
Resolvido no [PR](https://github.com/TiendaNube/nimbus-patterns/pull/32)
