### ISSUE TITLE
[REQUEST] Link - Text decoration opcional para appearance Neutral

### ISSUE THREAD

**Issue by Daniela-Lorenzetti** [TiendaNube/nimbus-design-system#137]
# Component - Link

- [ ] New component
- [x] New feature to an existing component

👨🏻‍💻👩🏻‍💻 **Team involved**

Who's the team or squad requesting this change. 
- Cross Business / Metafields

🗓 **Timeline**

Optionally, you can indicate a deadline for this to be ready.

📖 **Describe the feature or component**

No Nimbus 2.0 o componente "Link" permite que o link fique com _appearance: primary_ sem _text decoration (sublinhado) "[exemplo](exemplo)"_ e se selecionada a _appearance: neutral_ o _text decoration (sublinhado)_ é colocado como padrão, portanto não conseguimos usar o componente _neutral sem o text decoration_. 
Em Metafields estamos usando esse componente "link" com um chevron down ao lado para abrir um popover, nesse caso o componente não tem uma função totalmente relacionada a link portanto não seria necessário ter o text decoration.

✅ **Expected behavior**
O comportamento esperado é que possamos ter a opção de deixar o link com appearance: neutral sem o text decoration, que o text decoration seja opcional.

📷 **Sketches or UI design**

![Captura de Tela 2023-03-29 às 17 35 03](https://user-images.githubusercontent.com/83027073/228660995-2f0d1d19-2be0-4f1d-aeea-4feeea4e2350.png)

If available, add sketches, UI designs or link a design project that clearly showcases the component in use inside an interface.

❗️ **Additional context**

**Comment by diegopsilverio** [comment]
Olá @Daniela-Lorenzetti tudo bem?
De fato, esse problema do componente Link não ter a opção de ocultar o `text-decoration` no `appearance: neutral` está somente no Figma. No código, isso é possível de fazer: https://tiendanube.github.io/nimbus-design-system/?path=/docs/atomic-link--base
Você pode testar alterando as propriedades na tabela desta documentação. Já criei aqui uma task para corrigirmos o Figma.
Obrigado pelo issue!

**Comment by Daniela-Lorenzetti** [comment]
Maravilha @diegopsilverio. 
Obrigada pelo retorno ;)
