### ISSUE TITLE
[REQUEST] Add conditions to textAlign prop on Text component

### ISSUE THREAD

**Issue by juanchigallego** [TiendaNube/nimbus-design-system#146]
# Add conditions to `textAlign` prop on `Text` component

- [ ] New component
- [x] New feature to an existing component

👨🏻‍💻👩🏻‍💻 **Team involved**

Nimbus

📖 **Describe the feature or component**

Agregar conditions para utilizar en la propiedad `textAlign` del componente `Text`.

✅ **Expected behavior**

Debería funcionar así:

```jsx
<Text
  textAlign={{
    xs: "left",
    md: "right",
  }}
/>
```

❗️ **Additional context**

Este comportamiento es necesario para el pattern `EmptyMessage`.

📋 **Next Steps**

- [ ] Actualizar componente EmptyMessage usando esta nueva propiedad

**Comment by juniorconquista** [comment]
Resolved in PR #149
