### ISSUE TITLE
[BUG] Input append property overlaps the content of the text field

### ISSUE THREAD

**Issue by juanchigallego** [TiendaNube/nimbus-design-system#147]
🐛 **Describe the bug**
Cuando utilizamos la propiedad `append` con un valor de texto, este se superpone con el texto del placeholder o del valor del input. Esto es porque el padding izquierdo del input tiene un valor fijo y no toma en consideración el contenido variable que se puede introducir en el slot de `append`.

🧐 **To Reproduce**

1. Utilizar un componente `Input` con un texto largo dentro de la propiedad `append`
2. Colocar texto en la propiedad `placeholder`
3. Verificar que los textos se superponen

✅ **Expected behavior**
El padding izquierdo debería ser variable según el contenido ingresado en el `append`.

📷 **Screenshots**
| Cómo se ve | Cómo se debería ver |
|--------|--------|
| <img width="300" alt="Captura de pantalla 2023-04-12 a la(s) 13 18 01" src="https://user-images.githubusercontent.com/25963096/231519817-5197c29f-06cf-41c0-a3a3-37dc0c236b3d.png"> | <img width="300" alt="Captura de pantalla 2023-04-12 a la(s) 13 18 23" src="https://user-images.githubusercontent.com/25963096/231519821-404f1d28-ac48-488e-924a-46203259ff42.png"> |

**Comment by juniorconquista** [comment]
Resolved in PR #149
