### ISSUE TITLE
[BUG] Card has an additional bottom margin when not using Footer

### ISSUE THREAD

**Issue by juanchigallego** [TiendaNube/nimbus-design-system#148]
🐛 **Describe the bug**
Cuando no utilizamos `Card.Footer` dentro de un `Card`, hay un margen inferior adicional.

🧐 **To Reproduce**

1. Crear un componente `Card` con contenido pero sin `Card.Footer`
2. Verificar que hay un margen adicional de 16px sobre el canto inferior

✅ **Expected behavior**
El margen no debería visualizarse.

📷 **Screenshots**
| Cómo se ve | Cómo se debería ver |
|--------|--------|
| <img width="400" alt="Captura de pantalla 2023-04-12 a la(s) 13 21 56" src="https://user-images.githubusercontent.com/25963096/231520693-572e9352-36f8-4486-bc2c-758771b96ec1.png"> | <img width="400" alt="Captura de pantalla 2023-04-12 a la(s) 13 22 13" src="https://user-images.githubusercontent.com/25963096/231520701-065a7e4b-dd9c-4051-823d-597b5f9fe9f3.png"> |

**Comment by juniorconquista** [comment]
Resolved in PR #149
