### ISSUE TITLE
[BUG] Input from v1 with inconsistent height

### ISSUE THREAD

**Issue by jcampos89** [TiendaNube/nimbus-design-system#155]
🐛 **Describe the bug**
The input in Nimbus V1 is 2 pixels bigger than in V2, this makes the input bigger than the filter button on new admin.
![image (4)](https://user-images.githubusercontent.com/88346243/236531640-c5aef852-98eb-47fb-bff6-2edb33254f13.png)

🧐 **To Reproduce**

1. Go to [Storybook V1](https://tiendanube.github.io/design-system-nimbus/?path=/story/atomic-components-input--default-story)
2. Inspect the input height
3. Compare with [Storybook V2](https://tiendanube.github.io/nimbus-design-system/?path=/story/atomic-input--base)

✅ **Expected behavior**
The V1 input should only have 32px of height.

**Comment by juniorconquista** [comment]
Resolvido!
