### ISSUE TITLE
[REQUEST] Opção de "value" nos campos de formularios

### ISSUE THREAD

**Issue by huapp-dev** [TiendaNube/nimbus-design-system#160]
# Name of the feature or component

- [ ] New component
- [x] New feature to an existing component

👨🏻‍💻👩🏻‍💻 **Team involved**

Huapps, parceiro

🗓 **Timeline**

Optionally, you can indicate a deadline for this to be ready.

📖 **Describe the feature or component**

Atualmente utilizamos Svelte/SvelteKit para desenvolver o front-end dos nosso apps, para rodar o Nimbus utilizamos a biblioteca "svelte-preprocess-react": "^0.14.1" que renderiza o React dentro do Svelte.

Porem no svelte trabalhamos da seguinte maneira, vou tentar dar um exemplo:

let FORM = {campo1: "", campo2: "", campo3: "", ....}

<input type="text" bind:value={FORM.campo1} {placeholder} class={`nimbus-input_input ${classList.join(' ')}`} {disabled} {...rest}/>

no Svelte o bind: ele automaticamente faz as alterações na variável que recebe o "value", desta forma fica reativo de uma forma mais simplificada.

Porem como os componentes de formulario Nimbus não tem esta propriedade não conseguimos usar, nesse exemplo eu fiz um componente direto no svelte utilizando a estrutura HTML do Nimbos.

✅ **Expected behavior**

Seria muito mais simples para nos se fosse assim:

COMPONENTE INPUT
<Input appearance="success" placeholder="Placeholder" **bind:value={FORM.campo1}** />

**Comment by juniorconquista** [comment]
@huapp-dev fiquei com uma duvida no caso a prop que você gostaria de adicionar é `bind:value` ou `value`?

**Comment by juniorconquista** [comment]
@huapp-dev ótimo entendi vamos lá, creio que talvez por uma falha nossa documentação não deixa muito claro que todos os componentes herdam os tipos nativos do html sendo assim no caso do imput ele tem toda a api nativa do brownser o que inclui a prop value então basta enviar a prop value e tudo deve correr bem. No caso do input além do value ele tem todas as props do link a seguir.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
