### ISSUE TITLE
[BUG] Sidebar não fecha no mobile no onClick do overlay

### ISSUE THREAD

**Issue by vrlopess** [TiendaNube/nimbus-design-system#175]
🐛 **Describe the bug**
Sidebar não fecha no onClick do overlay (mobile)

📷 **Screenshots**
![image](https://github.com/TiendaNube/nimbus-design-system/assets/87648920/b6eab321-bc12-49bf-9025-3ee0c4abf5c4)

**Comment by juniorconquista** [comment]
@vrlopess muito obrigado por reportar esse bug, ele foi resolvido na PR https://github.com/TiendaNube/nimbus-design-system/pull/180
