### ISSUE TITLE
[REQUEST] Nuevo icon para subcategorías

### ISSUE THREAD

**Issue by carlosarmada** [TiendaNube/nimbus-design-system#190]
# Subcategory icon

- [ ] New component
Icon

👨🏻‍💻👩🏻‍💻 **Team involved**
CORE - New Admin

🗓 **Timeline**
22/09

📖 **Describe the feature or component**
En el listado de categorías actualmente podemos adicionar subcategorías, ahora estamos agregando la posibilidad de adicionar categorías principales (en el listado de categorías). Ante esta situación necesitamos un icon que puede diferenciarse del que ya usamos para agregar [Plus circle] para poder diferenciar uno de otro.

✅ **Expected behavior**

A clear and concise description of what you expect the component/feature to do.

📷 **Sketches or UI design**
[Link a figma](https://www.figma.com/file/36xsPocVwfEu1nNxQykwI8/%F0%9F%8F%B7-Catalog-%2F-Subdirectory-icon?type=design&node-id=402-77159&mode=design&t=4gIHj77oq7r1rFM7-4)

📋 **Next Steps**

**Comment by juanchigallego** [comment]
Added in #211
