### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by santigandolfo** [TiendaNube/nimbus-design-system#192]
🐛 **Describe the bug**
The modal component doesn't respect the Dark Mode theme

🧐 **To Reproduce**

1. Go to this [page](https://nimbus.tiendanube.com/es-AR/documentation/composite-components/modal) in the nimbus docs
2. Set Dark Mode

✅ **Expected behavior**
The modal should respect Dark Mode.

📷 **Screenshots**

![Screenshot 2023-09-19 at 14 12 09](https://github.com/TiendaNube/nimbus-design-system/assets/9329651/86ad13a9-ab7a-4d53-ad7e-ea4a0432aaf3)

🖥 **Desktop (please complete the following information):**

- OS: macOS 13.5.2
- Browser: Chrome
- Version: 117.0.5938.88

**Comment by juniorconquista** [comment]
@santigandolfo muito obrigado por reportar o bug foi corrigo na #203.
