### ISSUE TITLE
[BUG] MultiSelect selected options use an internal state instead of the passed in

### ISSUE THREAD

**Issue by mrolando-tn** [TiendaNube/nimbus-design-system#206]
🐛 **Describe the bug**
When passing the selected values to the MultiSelect component via the "value" prop, the component ignores them completely and instead relies on its internal "selectedOptions" State to render them. This is a problem because any change to the selected options that does not come from interacting with the MultiSelect component directly results in the selected options not updating visually in the component.

See https://github.com/TiendaNube/nimbus-design-system/pull/203/files#diff-70e6ba0a87571c7e0e096421480f3d555170f0fa807d6f10922945acbc200e5eR26

🧐 **To Reproduce**
Create a state "values" via useState and pass that into the "values" prop of the component. Use the setValues as the handleChange value of the prop. When modifying the state in anyway external to the component via the "setValues", the MultiSelect component will keep showing the values that were selected in the UI instead of the ones in the "values" state that we passed it.

✅ **Expected behavior**
It should not rely on an internal state for the selectedOptions. Instead it should use the value it receives via the "value" prop. It think the solution would be to replace useState([]) with useState(value), with value as the received prop, exactly how it is being done with the availableOptions.

📷 **Screenshots**

🖥 **Desktop (please complete the following information):**

📱 **Smartphone (please complete the following information):**

❗️ **Additional context**

**Comment by juanchigallego** [comment]
Fixed in #212
