### ISSUE TITLE
[BUG] FileUploader is not exported from components

### ISSUE THREAD

**Issue by AlissonEnz** [TiendaNube/nimbus-design-system#78]
🐛 **Describe the bug**

There is an issue with the component FileUploader. It's not working inside the package `@tiendanube/components` neither on `@nimbus-ds/file-uploader`. I was taking a look at the file on `node_modules` and there is no `dist` folder, so I believe for some reason it was not built correctly before uploading to `npm`.

🧐 **To Reproduce**

1. Clone the start project
2. Try to use the FileUploader component

✅ **Expected behavior**

Be able to use the component FileUploader

📷 **Screenshots**

Not applicable.

🖥 **Desktop (please complete the following information):**

- OS: Mac 13.1
- Browser Chrome
- Version 109

❗️ **Additional context**

I tested using `@tiendanube/components` on version `2.1.1` and `3.0.2`, and `@nimbus-ds/file-uploader` on version `2.0.0`

**Comment by juniorconquista** [comment]
@AlissonEnz Thank you very much for reporting this bug, a few days ago we had a problem in our package building process which caused the issue you reported. The problem has already been fixed and you can resolve it as follows. if using `@nimbus-ds/file-uploader` use version `2.1.0` and if using `@nimbus-ds/components` use version 2.3.0`. `@tiendanube/components` is v1 of nimbus, so you probably haven't found it.

**Comment by AlissonEnz** [comment]
Hi @juniorconquista, thanks for your quick reply.

It worked but I had to use `yarn` to install cause `npm` was throwing an error. I tried to install some `@nimbus-ds/` packages using `npm` but they all failed with this issue:

```bash
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^
```

My suggestion is to use yarn on this sample application (https://github.com/TiendaNube/in-admin-app/tree/master/react) to prevent issues for future developers.

And, thanks again, it's a great library 👏🏼

**Comment by juniorconquista** [comment]
HI @AlissonEnz, thank you very much for letting us know about this new incident, I just checked the reason and it's already solved, just install the latest version I just posted `@nimbus-ds/file-uploader` version `2.3.0`.

And feel free to use `npm` if you prefer and the problem won't happen again.

Thanks again and sorry for the new incident.
